_format_version: "1.1"
_workspace: default
consumers:
- custom_id: "112345"
  username: shameemshamsuddin
services:
- connect_timeout: 60000
  enabled: true
  host: reqres.in
  name: singleuser
  path: /api/users/2
  port: 443
  protocol: https
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: singleuser
    path_handling: v0
    paths:
    - /singleuser
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
- connect_timeout: 60000
  enabled: true
  host: reqres.in
  name: users
  path: /api/users
  plugins:
  - config:
      day: null
      fault_tolerant: true
      header_name: null
      hide_client_headers: false
      hour: 120
      limit_by: ip
      minute: 2
      month: null
      path: null
      policy: cluster
      redis_database: 0
      redis_host: null
      redis_password: null
      redis_port: 6379
      redis_server_name: null
      redis_ssl: false
      redis_ssl_verify: false
      redis_timeout: 2000
      redis_username: null
      second: null
      year: null
    enabled: true
    name: rate-limiting
    protocols:
    - grpc
    - grpcs
    - http
    - https
  port: 443
  protocol: https
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    name: users
    path_handling: v0
    paths:
    - /users
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
